#!/usr/bin/env python
# A simple timer program used to feed Mags

import time
from playsound import playsound
from subprocess import call

def timer(sec=int(input("How many seconds? "))):
    while seconds > 0:
        if seconds == 30:
            print("30 SECONDS REMAINING...")
        if seconds in range(11):
            print(sec)
        if seconds == 1:
            playsound('C:/Users/kamik/code/projects/pso_timer/sounds/feedingJingle+buffer.mp3') # 24sec long
            call('clear')
            seconds = 196 # restarts countdown and adds 25 seconds buffer for feeding time


    time.sleep(1) # every second
    seconds -= 1 # remove one second
timer()
